In [200]:
#use of lambda function
lst=[(3,'c'),(1,'a'),(2,'b'),(2,'a'),(1,'b'),(3,'a')]
a=sorted(lst,key=lambda x:(-ord(x[1]),x[0]))
print(a)

[(3, 'c'), (1, 'b'), (2, 'b'), (1, 'a'), (2, 'a'), (3, 'a')]


In [7]:
#print the strings which have size greater than 5
strings = ["apple", "banana", "cherry", "date", "fig", "grape"]
filtered_strings = list(filter(lambda s: len(s) > 5, strings))
print(filtered_strings)

['banana', 'cherry']


In [26]:
#accessin the first element of the first row of the first column in 3d array
import numpy as np
ar=np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
l=ar[0,0,0]
print(l)

1


In [36]:
#the sum of the integers
def calculate_sum_of_integers():
    total_sum = 0
    
    while True:
        try:
            num_str = input("Enter an integer (or 'q' to quit): ")
            
            if num_str == 'q':
                break
            
            num = int(num_str)
            total_sum += num
            
        except ValueError:
            print("Error: Please enter a valid integer. Ignoring this input.")
    
    return total_sum

# Calculate the sum of integers entered by the user
total_sum = calculate_sum_of_integers()
print(f"The sum of the integers entered is: ",total_sum)

Enter an integer (or 'q' to quit):  1
Enter an integer (or 'q' to quit):  2
Enter an integer (or 'q' to quit):  3
Enter an integer (or 'q' to quit):  e


Error: Please enter a valid integer. Ignoring this input.


Enter an integer (or 'q' to quit):  q


The sum of the integers entered is:  6


In [30]:
#accessing elements from the 2d array
n=np.array([[1,2,3],
            [4,5,6],
            [7,8,9],
            [10,11,12]])
a=n[1,1]
b=n[2,1]
print(a)
print(b)

5
8


In [8]:
# file operations in python
f=open("abc.txt","w")
f.write("\n1\n2\n3\n4\n")
l=[]
count=1
f=open("abc.txt","r")
for i in f.read():
    if(i!='\n'):
        j=int(i)
        l.append(j)
avg=sum(l)/len(l)
print(avg)
try:
    f1=open("xyz.txt")
    a=10/0
except FileNotFoundError:
    print("error: the file is not present")
except ZeroDivisionError:
    print("error: cannot be divided by zero")

2.5
error: the file is not present


In [25]:
#usage of re module
text = 'Please email us at info@example.com or support@example.com'
email_addresses = re.findall('[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', text)
print(email_addresses)


['info@example.com', 'support@example.com']


In [148]:
#removing stop keywords
import re
import nltk
text = 'this is an apple and those are bananas '
pattern = r'\b(?:a|an|...|now)\b'
cleaned_text = re.sub(pattern, ' ', text)
cleaned_text = re.sub(r'\s+', ' ', cleaned_text).strip()
print(cleaned_text)

this apple those bananas


In [164]:
#accessing the last element of the last row of the last column
n=np.random.randint(10,size=(4,4,4))
print(n)
y=n[3,3,3]
print(y)

[[[6 0 4 5]
  [9 3 0 2]
  [1 8 0 4]
  [0 3 6 3]]

 [[3 0 2 5]
  [0 4 9 3]
  [2 3 4 7]
  [4 4 5 5]]

 [[5 6 4 6]
  [4 8 7 3]
  [3 6 4 0]
  [6 8 6 6]]

 [[3 1 1 4]
  [5 0 4 6]
  [7 5 1 1]
  [5 9 4 6]]]
6


In [174]:
#dictionary comprehensions
a={n:n**2  for n in range(2,21,2)}
a

{2: 4,
 4: 16,
 6: 36,
 8: 64,
 10: 100,
 12: 144,
 14: 196,
 16: 256,
 18: 324,
 20: 400}

In [179]:
n=np.array([[1,10,3],
            [3,5,9]])
y=n[0,1]
print(y)

10


In [184]:
arr=np.empty((3,1,2))
arr

array([[[8.48798317e-314, 1.27319747e-313]],

       [[1.48539705e-313, 6.36598738e-314]],

       [[2.12199580e-314, 1.27319747e-313]]])

In [199]:
#dictionary comprehension to print first 10 prime numbers
primes = {x for x in range(2, 11) if all(x % i  for i in range(2, int(x**0.5) +1 ))}
print(primes)

{2, 3, 5, 7}


In [201]:
n=['taruni','dev','dee','chash']
y=list(sorted(n))
y

['chash', 'dee', 'dev', 'taruni']

In [202]:
#zipping keys and values
keys = ['a', 'b', 'c', 'a', 'c']
values = [1, 2, 3, 4, 5]

result = {}
for key, value in zip(keys, values):
    result.setdefault(key, []).append(value)

print(result)

{'a': [1, 4], 'b': [2], 'c': [3, 5]}
