In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [7]:
a=["taruni",3,4,3.0,0,False]
d=np.array(a,dtype=bool)
print(d)

[ True  True  True  True False False]


In [5]:
a=np.array([1,2,3,3,4,4,6])
b=np.extract(a<4,a)
print(b)

[1 2 3 3]


In [9]:
a=np.array([1,2,3,4,4,5,6,7,8,9,10])
b=np.where(a>3,111,a)
print(b)

[  1   2   3 111 111 111 111 111 111 111 111]


In [10]:
a=np.arange(16)
b=np.where(a%2==0,111,a)
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[111   1 111   3 111   5 111   7 111   9 111  11 111  13 111  15]


In [12]:
a=np.arange(16)
b=a.reshape(4,4)
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [15]:
a=np.arange(16)
b=np.where((a>3) &(a<13))
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(array([ 4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64),)


In [28]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[6,7,8],[9,10,11]])
c=np.vstack((a,b))
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 6  7  8]
 [ 9 10 11]]


In [29]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[6,7,8],[9,10,11]])
c=np.hstack((a,b))
print(c)

[[ 1  2  3  6  7  8]
 [ 4  5  6  9 10 11]]


In [32]:
a=np.array([1,2,3,4,5])
b=np.array([3,4,5,6,7])
c=np.intersect1d(a,b)
print(c)

[3 4 5]


In [33]:
a=np.array([1,2,3,4,5])
b=np.array([3,4,5,6,7])
c=np.setdiff1d(a,b)
print(c)

[1 2]


In [3]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.where(a>3)
print(b)

(array([3, 4], dtype=int64),)


In [59]:
a=np.array([[1,2,3,4],[5,6,7,8]])
b=a.reshape(1,-1)
print("reshaping:",b)

reshaping: [[1 2 3 4 5 6 7 8]]


In [58]:
a=np.arange(9).reshape(3,3)
print(a)
print("after swapping:")
a[:,[2,1,0]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
after swapping:


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [8]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=np.mean(a)
c=np.median(a)
d=np.std(a)
print("mean :",b)
print("median :",c)
print("standardization :",d)

mean : 5.0
median : 5.0
standardization : 2.581988897471611


In [57]:
a=np.arange(101)
p=np.percentile(a,q=[10,11])
print("percentile :",p)

percentile: [10. 11.]


In [73]:
x=np.array([1,2,3,4,5,6])
y=np.array([6,5,4,3,2,1])
dist=np.linalg.norm(x-y)
print("euclidean distance :",dist)

euclidean distance: 8.366600265340756


In [51]:
import random
a=np.random.randint(0,100,500)
b=a+np.random.randint(0,100,500)
corr=np.corrcoef(a,b)
print("correlation :",corr)

correlation: [[1.         0.70330132]
 [0.70330132 1.        ]]


In [96]:
a=np.array(['a','b','c','d','e'])
b=np.array([1,2,3,4,5])
b=b/b.sum()
s=np.random.choice(a,size=4,p=b)
print("probabiliatic sample :",s)

probabiliatic sample : ['e' 'b' 'c' 'd']


In [98]:
n=np.random.randint(10,size=10)
movavg=np.convolve(x,np.ones(3)/3,mode='valid')
print(n)
print("moving average :",movavg)

[4 2 9 8 2 0 9 4 9 9]
moving average : [2. 3. 4. 5.]


In [101]:
n=np.array([[1,2,3],[4,np.nan,5]])
np.argwhere(np.isnan(n))

array([[1, 1]], dtype=int64)

In [115]:
a=np.array([[1,2,3],[4,5,np.nan]])
a[~np.isnan(a).any(axis=1)]

array([[1., 2., 3.]])

In [122]:
a=np.array([[1,2,3],
            [7,8,np.nan]])
a[np.isnan(a)]=0
print(a)

[[1. 2. 3.]
 [7. 8. 0.]]


In [120]:
a=np.array([[1,2,3],
            [3,4,np.nan]])
a[~np.isnan(a)]

array([1., 2., 3., 3., 4.])

In [134]:
a=np.array([1,2,3,4,5,6])
b=(a-np.min(a))/(np.max(a)-np.min(a))
print("normalization :",b)

normalization : [0.  0.2 0.4 0.6 0.8 1. ]


In [141]:
a=np.random.randint(16,size=16)
a=a.reshape(4,4)
print(a)
a=a.min(axis=1)/a.max(axis=1)
print("min-by-max:",a)

[[ 2  1  1  8]
 [ 1  0 12 13]
 [14  7  8  3]
 [ 3  7 13  9]]
min-by-max: [0.125      0.         0.21428571 0.23076923]


In [151]:
import pandas as pd
a=pd.Series([1,2,3])
print(a)

0    1
1    2
2    3
dtype: int64


In [153]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=pd.Series(a)
print(b)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int32


In [154]:
a=({"a":1,"b":2,"c":3,"d":4})
b=pd.Series(a)
print(b)

a    1
b    2
c    3
d    4
dtype: int64


In [156]:
a=({"a":1,"b":2,"c":3,"d":4})
b=pd.Series(a)
c=b.to_frame().reset_index()
print(c)

  index  0
0     a  1
1     b  2
2     c  3
3     d  4


In [169]:
a=pd.Series(['a','b','c'],name='sample1')
b=pd.Series(['d','e','f'],name='sample2')
d=pd.concat([a,b],axis=1)
print("concatinating two many series to form a dataframe:")
print(d)

concatinating two many series to form a dataframe:
  sample1 sample2
0       a       d
1       b       e
2       c       f


In [171]:
a=pd.DataFrame({"col1":[1,2,3],"col2":[4,5,6]})
xnorm=(a-np.min(a))/(np.max(a)-np.min(a))
print("normalization in pandas:")
print(xnorm)

normalization in pandas:
   col1  col2
0   0.0   0.6
1   0.2   0.8
2   0.4   1.0


In [174]:
data=pd.DataFrame({
        'a':[1,2,3,4,5],
        'b':[2,3,4,5,6],
        'c':[3,4,5,6,7]})
print(data)
correlation_with_next_row=data.corrwith(data.shift(-1))
print("correlation_with_next_row:")
print(correlation_with_next_row)

   a  b  c
0  1  2  3
1  2  3  4
2  3  4  5
3  4  5  6
4  5  6  7
correlation_with_next_row:
a    1.0
b    1.0
c    1.0
dtype: float64


In [177]:
import pandas as pd 
import numpy as np
num_series=pd.Series(np.random.randint(1,100,100))
auto_correlation=num_series.autocorr()
print("num_series:")
print(num_series)
print("auto_correlation with lag 1:")
print(auto_correlation)

num_series:
0     32
1     62
2     54
3     86
4     67
      ..
95    92
96    19
97    98
98    81
99    39
Length: 100, dtype: int32
auto_correlation with lag 1:
0.0863181566193701
